[book]
title = "GRW — Graph Rewriting in Rust"
authors = ["Karol Skocik"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/grw-rs/grw"
additional-css = ["theme/custom.css"]
additional-js = []
playground.runnable = false
